### ISSUE TITLE
Read-only file system

### ISSUE THREAD

**Issue by bank5ia** [w0lfschild/vpk#2]
Every time I try to do anything, I will keep getting an error message. Read-Only file system. I have tried everything I know but to no success. I'm using MacOS Mojave, my SIP is enabled (if that even matters) and i was trying to open a file called portal_pak_dir.vpk

plz help me. what am i doing wrong
<img width="512" alt="Screen Shot 2020-04-24 at 12 46 31 pm" src="https://user-images.githubusercontent.com/60557828/80169866-ead79700-8629-11ea-924c-4694fa7e4c59.png">

**Comment by w0lfschild** [comment]
Where are you launching the application from?

Try running from `/Applications`
